version: '3.7'

services:

  db:
    container_name: esgipostgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  server:
    container_name: esgiserver
    image: ghcr.io/cenmelt/favorite-place-server:latest
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: supersecret
      DB_NAME: postgres
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - app-network

  client:
    container_name: esgiclient
    image: ghcr.io/cenmelt/favorite-place-client:latest
    ports:
      - 801:80
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
